CREATE TABLE IF NOT EXISTS NAMES (
    name_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    gender CHAR(1) NOT NULL CHECK (gender IN('M', 'F'))
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS DETAILS (
    details_id INT AUTO_INCREMENT PRIMARY KEY,
    name_id REFERENCES NAMES(name_id) ON DELETE CASCADE,
    year INT NOT NULL,
    count INT NOT NULL
    created_at TIMESTAMP DEFAULT NOW()
    updated_at TIMESTAMP DEFAULT NOW()
);