CREATE TABLE IF NOT EXISTS NAME (
    name_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    gender CHAR(1) NOT NULL CHECK (gender IN('M', 'F'))
);

CREATE TABLE IF NOT EXISTS DETAIL (
    details_id INT AUTO_INCREMENT PRIMARY KEY,
    name_id REFERENCES NAMES(name_id) ON DELETE CASCADE,
    year INT NOT NULL,
    count INT NOT NULL
);